import streamlit as st
import plotly.express as px
from PIL import Image

from dashboard.utils.loaders import load_embeddings, load_figure_path
from dashboard.utils.styles import get_plotly_theme


def render_embedding_visualization() -> None:
    st.markdown(
        """
        <div class='section-card'>
            <div class='section-title'>Embedding Analysis</div>
            <div class='section-subtitle'>Explore the learned node representation space generated by the graph neural networks.</div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    model_choice = st.selectbox("Model", ["GCN", "GraphSAGE"], index=0)
    embedding_df = load_embeddings(model_choice)
    if embedding_df is None or embedding_df.empty:
        st.error(f"Embedding data for {model_choice} is currently unavailable.")
        return

    if "x" not in embedding_df.columns or "y" not in embedding_df.columns:
        st.error("Embedding file is missing coordinate columns.")
        return

    theme = st.session_state.get("theme", "light")
    plot_theme = get_plotly_theme(theme)

    if "label" not in embedding_df.columns:
        st.warning("Embedding file does not contain class labels.")
        label_col = None
    else:
        label_col = "label"

    sample_size = min(3000, len(embedding_df))
    if len(embedding_df) > sample_size:
        sample_df = embedding_df.sample(sample_size, random_state=42)
        st.info(f"Showing {sample_size:,} of {len(embedding_df):,} points for performance.")
    else:
        sample_df = embedding_df

    fig = px.scatter(
        sample_df,
        x="x",
        y="y",
        color=label_col,
        hover_data={"node_id": True} if "node_id" in sample_df.columns else {},
        labels={"x": "Component 1", "y": "Component 2"},
    )
    fig.update_layout(
        margin=dict(l=10, r=10, t=30, b=10),
        height=500,
        paper_bgcolor=plot_theme["paper_bgcolor"],
        plot_bgcolor=plot_theme["plot_bgcolor"],
        font=dict(color=plot_theme["font_color"]),
        xaxis=dict(gridcolor=plot_theme["grid_color"]),
        yaxis=dict(gridcolor=plot_theme["grid_color"]),
    )
    st.plotly_chart(fig, use_container_width=True)

    summary_cols = st.columns(4)
    summary_items = [
        ("Embedded Nodes", f"{len(embedding_df):,}"),
        ("Classes Present", int(embedding_df["label"].nunique()) if "label" in embedding_df.columns else "—"),
        ("Model", model_choice),
        ("Method", "PCA"),
    ]
    for col, (label, value) in zip(summary_cols, summary_items):
        with col:
            st.markdown(
                f"""
                <div class='kpi-card'>
                    <div class='metric-label'>{label}</div>
                    <div class='metric-value'>{value}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )

    st.markdown("<div class='section-card'><div class='section-title'>t-SNE Analysis</div><div class='section-subtitle'>A non-linear projection of the same representation space.</div></div>", unsafe_allow_html=True)
    tsne_path = load_figure_path("gcn_tsne_embeddings.png")
    if tsne_path is not None:
        try:
            st.image(Image.open(tsne_path), use_container_width=True)
        except Exception:
            st.info("Could not load t-SNE visualization.")
    else:
        st.info("t-SNE visualization not available (only GCN t-SNE is provided in the project).")
